// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Run 'npm run sync:permissions' to update.

export const PERMISSIONS = {
  // DELIVERY ZONES
  VIEW_DELIVERY_ZONES: 'VIEW_DELIVERY_ZONES',
  CREATE_DELIVERY_ZONES: 'CREATE_DELIVERY_ZONES',
  UPDATE_DELIVERY_ZONES: 'UPDATE_DELIVERY_ZONES',
  DELETE_DELIVERY_ZONES: 'DELETE_DELIVERY_ZONES',
  // ROLES
  VIEW_ROLES: 'VIEW_ROLES',
  CREATE_ROLES: 'CREATE_ROLES',
  UPDATE_ROLES: 'UPDATE_ROLES',
  DELETE_ROLES: 'DELETE_ROLES',
  // VENDORS
  VIEW_VENDORS: 'VIEW_VENDORS',
  CREATE_VENDORS: 'CREATE_VENDORS',
  UPDATE_VENDORS: 'UPDATE_VENDORS',
  DELETE_VENDORS: 'DELETE_VENDORS',
  // ADMINS
  VIEW_ADMINS: 'VIEW_ADMINS',
  CREATE_ADMINS: 'CREATE_ADMINS',
  UPDATE_ADMINS: 'UPDATE_ADMINS',
  DELETE_ADMINS: 'DELETE_ADMINS',
  // CATEGORIES
  VIEW_CATEGORIES: 'VIEW_CATEGORIES',
  CREATE_CATEGORIES: 'CREATE_CATEGORIES',
  UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
  DELETE_CATEGORIES: 'DELETE_CATEGORIES',
  APPROVE_CATEGORIES: 'APPROVE_CATEGORIES',
  // BRANDS
  VIEW_BRANDS: 'VIEW_BRANDS',
  CREATE_BRANDS: 'CREATE_BRANDS',
  UPDATE_BRANDS: 'UPDATE_BRANDS',
  DELETE_BRANDS: 'DELETE_BRANDS',
  APPROVE_BRANDS: 'APPROVE_BRANDS',
  // CUSTOMERS
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  UPDATE_CUSTOMERS: 'UPDATE_CUSTOMERS',
  // COURIERS
  VIEW_COURIERS: 'VIEW_COURIERS',
  UPDATE_COURIERS: 'UPDATE_COURIERS',
  DELETE_COURIERS: 'DELETE_COURIERS',
  APPROVE_COURIERS: 'APPROVE_COURIERS',
  // MASTER PRODUCTS
  VIEW_MASTER_PRODUCTS: 'VIEW_MASTER_PRODUCTS',
  CREATE_MASTER_PRODUCTS: 'CREATE_MASTER_PRODUCTS',
  UPDATE_MASTER_PRODUCTS: 'UPDATE_MASTER_PRODUCTS',
  DELETE_MASTER_PRODUCTS: 'DELETE_MASTER_PRODUCTS',
  APPROVE_MASTER_PRODUCTS: 'APPROVE_MASTER_PRODUCTS',
  // ORDERS
  VIEW_ORDERS: 'VIEW_ORDERS',
  CANCEL_ORDERS: 'CANCEL_ORDERS',
  // HOT ZONES
  VIEW_HOT_ZONES: 'VIEW_HOT_ZONES',
  CREATE_HOT_ZONES: 'CREATE_HOT_ZONES',
  UPDATE_HOT_ZONES: 'UPDATE_HOT_ZONES',
  DELETE_HOT_ZONES: 'DELETE_HOT_ZONES',
  // FINANCES
  VIEW_FINANCES: 'VIEW_FINANCES',
  // SETTLEMENTS
  MANAGE_SETTLEMENTS: 'MANAGE_SETTLEMENTS',
  // PAYOUTS
  MANAGE_PAYOUTS: 'MANAGE_PAYOUTS',
  // REFUNDS
  MANAGE_REFUNDS: 'MANAGE_REFUNDS',
  // SYSTEM SETTINGS
  MANAGE_SYSTEM_SETTINGS: 'MANAGE_SYSTEM_SETTINGS',
  // COURIER TO ORDER
  ASSIGN_COURIER_TO_ORDER: 'ASSIGN_COURIER_TO_ORDER',
  // ORDER STATUS
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
